### ISSUE TITLE
Feature request - mirror input

### ISSUE THREAD

**Issue by dgcliff** [lornix/fauxcon#7]
First of all, thanks for this utility, it works great!

I was just wondering if there could be a feature/flag that would allow the input to be output to the screen. Using things like ttylog seems to cause fauxcon to stop working unfortunately.

**Comment by lornix** [comment]
Hmmm, like a local echo?

Had to look up ttylog... Serial port log to stdout or a file.  Ok...

Definitely doable.  I'll need to review fauxcon a bit to get back up to
speed (yeah, reasons).

I'm curious about your usage of fauxcon and ttylog, and any potential
interaction.  Could you give me a (brief) scenario, with command lines
showing options?

Thank you

Loni

**Comment by dgcliff** [comment]
Sure, happy to.

I have a computer in a rack with a monitor attached. Typing at the console involves physically going there. Instead, I SSH from my desk, and use fauxcon to type.

```sudo fauxcon -C```

The only output visible at the SSH is ```Reminder: Escape sequence is '<CR> % .'``` which means I need to be able to see the rack monitor, or have pretty good faith that I'm typing correctly.

If it were possible to see what I was typing underneath ```Reminder...``` it'd make it a ton more useful

The reason why I need fauxcon is that screen, tmux etc. don't play nice with X server. Whenever I start it that way, my bluetooth device doesn't give input.

**Comment by dgcliff** [comment]
Ah, I just realized that ```-vv``` does what I want (should've read  -help better!)

Thanks!

**Comment by lornix** [comment]
No worries.
